version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: fleet_management
      MYSQL_USER: root
      MYSQL_PASSWORD: mysecretpassword1234
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fleet_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: